{% set name = "opentelemetry-instrumentation-writer" %}
{% set version = "0.57.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 28a46091cfd9d88f2b05c10f21f5f858ed0cbe5643cb60cbbae3b2d72727b9a3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - opentelemetry-api >=1.38.0,<2.0.0
    - opentelemetry-semantic-conventions >=0.59b0
    - opentelemetry-instrumentation >=0.59b0
    - opentelemetry-semantic-conventions-ai <0.6.0,>=0.5
  run_constrained:
    - writer-sdk >=2.3.0,<3.0.0

# Unable to run tests and check imports, writer-sdk is not in the main channel.
test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.traceloop.com/openllmetry
  dev_url: https://github.com/traceloop/openllmetry
  doc_url: https://www.traceloop.com/docs/openllmetry/introduction
  summary: OpenTelemetry Writer instrumentation
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    This library allows tracing calls to any of Writer's endpoints sent with the official Writer Python Library.

extra:
  recipe-maintainers:
    - timkpaine
  skip-lints:
    - invalid_url
    - missing_imports_or_run_test_py
